# Copyright (c) 1999-2009, 2013-2018, 2020-2021 Paul Mattes.
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Paul Mattes nor his contributors may be used
#       to endorse or promote products derived from this software without
#       specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY PAUL MATTES "AS IS" AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
# NO EVENT SHALL PAUL MATTES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Makefile for playback utility

RM = rm -f
CC = gcc

all: playback

HOST = x86_64-unknown-linux-gnu

CCOPTIONS =  -Wall -Wsign-compare -std=c99 -pedantic -Wno-variadic-macros -MMD -MP
XCPPFLAGS = -I$(THIS) -I$(TOP)/include  -D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED
CFLAGS = $(CCOPTIONS) $(CDEBUGFLAGS) $(XCPPFLAGS) -ggdb3 -Werror -Wno-format-zero-length -fno-common
LDFLAGS = 
LIBS = 

playback: playback.o
	$(CC) -o $@ playback.o $(LDFLAGS)


clean:
	$(RM) *.o
clobber: clean
	$(RM) playback *.d

# Include auto-generated dependencies.
-include $(OBJS:.o=.d) mkfb.d
