# Copyright (c) 1999-2009, 2013-2016 Paul Mattes.
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Paul Mattes nor his contributors may be used
#       to endorse or promote products derived from this software without
#       specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY PAUL MATTES "AS IS" AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
# NO EVENT SHALL PAUL MATTES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Makefile for b3270 (scripted 3270 emulator)

RM = rm -f
CC = gcc

all: b3270

OBJ = o
HOST = x86_64-unknown-linux-gnu
include libs.mk

VOBJS = async.o b3270.o b_ft.o b_popups.o b_status.o fallbacks.o screen.o \
	ui_stream.o

OBJS1 = $(VOBJS) version.o

LIBDIR = ${exec_prefix}/lib
prefix = /usr/local
exec_prefix = ${prefix}
sysconfdir = ${prefix}/etc
datarootdir = ${prefix}/share
LIBX3270DIR = ${sysconfdir}/x3270
MANDIR = ${datarootdir}/man
BINDIR = ${exec_prefix}/bin
INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644

CCOPTIONS =  -Wall -Wsign-compare -std=c99 -pedantic -Wno-variadic-macros -MMD -MP
XCPPFLAGS = -I$(THIS) -I$(TOP)/include -I$(TOP)/Common/b3270 -DLIBX3270DIR=\"$(LIBX3270DIR)\" -D_POSIX_SOURCE
CFLAGS = $(CCOPTIONS) $(CDEBUGFLAGS) $(XCPPFLAGS)
LDFLAGS = 
LIBS = -lssl -lcrypto -lexpat -lutil 

XVERSION = xversion.c
version.o: mkversion.sh $(VOBJS) version.txt
	$(RM) $(XVERSION)
	sh $< b3270 $(filter %.txt,$^) >$(XVERSION)
	$(CC) $(CFLAGS) -c -o $@ $(XVERSION)
	$(RM) $(XVERSION)

FALLBACKS = fb-common
fallbacks.c: mkfb $(FALLBACKS)
	$(RM) $@
	./mkfb -c -o $@ $(filter-out mkfb,$^)

mkfb: mkfb.c
	$(CC) $(CFLAGS) -o $@ $(filter %.c,$^)

b3270: $(OBJS1) $(DEP3270) $(DEP32XX) $(DEP3270STUBS)
	$(CC) -o $@ $(OBJS1) $(LDFLAGS) $(LD3270) $(LD32XX) $(LD3270STUBS) $(LIBS)
install: b3270
	[ -d $(DESTDIR)$(BINDIR) ] || \
		mkdir -p $(DESTDIR)$(BINDIR)
	$(INSTALL_PROGRAM) b3270 $(DESTDIR)$(BINDIR)/b3270

install.man:
	[ -d $(DESTDIR)$(MANDIR)/man1 ] || \
		mkdir -p $(DESTDIR)$(MANDIR)/man1
	$(INSTALL_DATA) b3270.man $(DESTDIR)$(MANDIR)/man1/b3270.1
	$(INSTALL_DATA) x3270-script.man $(DESTDIR)$(MANDIR)/man1/x3270-script.1

clean:
	$(RM) *.o mkfb
clobber: clean
	$(RM) b3270 *.d

# Include auto-generated dependencies.
-include $(OBJS:.o=.d) mkfb.d
