'\" t
.TH PR3287 1 "20 March 2024"
.SH "NAME"
pr3287 \-
\s-1IBM\s+1
host printing tool
.SH "SYNOPSIS"
\fBpr3287\fP
[\fIoptions\fP] \fIhostname\fP
.SH "DESCRIPTION"
\fBpr3287\fP
opens a TELNET connection to an
\s-1IBM\s+1
host, and emulates an \s-1IBM\s+1 3287 printer.
It implements RFCs 2355 (TN3270E), 1576 (TN3270) and 1646 (LU name selection).
.SH "WIKI"
Primary documentation for pr3287 is on the \fBx3270 Wiki\fP, https://x3270.miraheze.org/wiki/Main_Page.
.SH "VERSION"
pr3287 4.4pre1
