#!/bin/bash

# Check the OpenSSL DLL link.

link="Win32OpenSSL_Light"
urlfile=Webpage/openssl-url.txt

# Check that we are in the right place.
if [ ! -f $urlfile ]
then	echo >&2 "Must run from top of tree."
    	exit 1
fi

# Get the URL.
url=$(<$urlfile)

# Set up the temp file.
tf=/tmp/ch.$$
rm -f $tf
rc=0

# See if it's accessible.
if wget $url -O /dev/null >$tf 2>&1
then	echo "The link is still good."
else	echo "*** FAILURE ***"
	cat $tf
    	rc=1
fi

rm -f $tf
exit $rc
