#!/bin/bash
# Check for out-of-date copyrights

svn list -R | while read f
do	case $f in
    	*/)	continue
		;;
	esac
    	if svn log $f | grep 2008- >/dev/null
	then	if grep 'Copyright.*2008' $f >/dev/null
		then :
		else	echo $f
		fi
	fi
done
