'\" t
.TH c3270 1 "20 March 2024"
.SH "NAME"
c3270 \-
curses-based 
\s-1IBM\s+1 host access tool
.SH "SYNOPSIS"
\fBc3270\fP
[\fIoptions\fP]
[\fIhost\fP]
.br
\fBc3270\fP [\fIoptions\fP] \fIsession-file\fP.c3270
.SH "DESCRIPTION"
\fBc3270\fP opens a telnet connection to an \s-1IBM\s+1
host in a console window.
It implements RFCs 2355 (TN3270E), 1576 (TN3270) and 1646 (LU name selection),
and supports IND$FILE file transfer.
If the console is capable of displaying colors, then \fBc3270\fP emulates an
\s-1IBM\s+1 3279.  Otherwise, it emulates a 3278.
.SH "WIKI"
Primary documentation for c3270 is on the \fBx3270 Wiki\fP, https://x3270.miraheze.org/wiki/Main_Page.
.SH "VERSION"
c3270 4.4pre1
