'\" t
.TH tcl3270 1 "20 March 2024"
.SH "NAME"
tcl3270 \-
\s-1IBM\s+1 host access tool
.SH "SYNOPSIS"
\fBtcl3270\fP
[\fIscript\fP [\fIscript-arg...\fP]] [-- [\fItcl3270-options\fP] [\fIs3270-options\fP] [\fIhost\fP]
.br
\fBtcl3270\fP
[\fIscript\fP [\fIscript-arg...\fP]] [-- [\fItcl3270-options\fP] [\fIs3270-options\fP] [\fIsession-file\fP.tcl3270]
.br
\fBtcl3270\fP -v
.br
\fBtcl3270\fP --help
.SH "DESCRIPTION"
\fBtcl3270\fP opens a telnet connection to an \s-1IBM\s+1
host, then allows a Tcl script to control the host login session.
It is derived from
\fIs3270\fP(1),
a script-based IBM 3270 emulator.
.LP
For each action supported by s3270, tcl3270 defines a
correcponding Tcl command.
The result of the Tcl command is the output of the s3270 action.
If the output is one line, the result is a string.
If the output is multiple lines, the result is a list of strings.
.LP
On the command line, a session file can be named either
\fIname\fP.\fBtcl3270\fP or \fIname\fP.\fBs3270\fP.
Resource values, such as those used in \fB\-xrm\fP options or in a
session file, can be specified as \fBtcl3270\fP.\fIresource\fP or
\fBs3270\fP.\fIresource\fP.
.SH "TCL3270-SPECIFIC OPTIONS"
.TP
\fB\-d\fP
Turns on debugging information, tracing data going between tcl3270 and
s3270.
.SH "SEE ALSO"
s3270(1)
.SH "WIKI"
Primary documentation for tcl3270 is on the \fBx3270 Wiki\fP, https://x3270.miraheze.org/wiki/Main_Page.
.SH "VERSION"
tcl3270 4.4pre1
