'\" t
.TH X3270IF 1 "20 March 2024"
.SH "NAME"
x3270if \- script interface to 3270 emulators
.SH "SYNOPSIS"
\fBx3270if\fP [option]... [ \fIaction\fP ]
.br
\fBx3270if\fP [option]... \-i
.br
\fBx3270if\fP [option]... \-I \fIemulator-name\fP [\-H \fIhelp-action\fP]
.SH "DESCRIPTION"
\fBx3270if\fP provides an interface between scripts and
the 3270 emulators x3270, c3270, wc3270 s3270 and b3270.
.SH "WIKI"
Primary documentation for x3270if is on the \fBx3270 Wiki\fP, https://x3270.miraheze.org/wiki/Main_Page.
.SH "VERSION"
x3270if 4.4pre1
