#!/usr/bin/env bash

if [ "x$1" = "x-v" ]
then	shift
    	version_txt=$1
	shift
	. $version_txt
fi

if [ "x$1" = "x-d" ]
then	shift
	dirnames=$1
	shift
	. $dirnames
fi

sed -e "s/%VERSION%/$version/g" -e "s/%CYEAR%/$cyear/g" -e "s/%WIN32%/$win32/g" -e "s/%WIN64%/$win64/g"
