# Copyright (c) 2026 Paul Mattes.
# All rights reserved.

# Auxiliary makefile for ntcl3270.

PRODUCT = ntcl3270

all:
	@echo "Must pick a specific make target."

prepare: configure
configure: configure.in
	autoconf
