#!/bin/bash
# Copyright 2000, 2003 by Paul Mattes.
#  Permission to use, copy, modify, and distribute this software and its
#  documentation for any purpose and without fee is hereby granted,
#  provided that the above copyright notice appear in all copies and that
#  both that copyright notice and this permission notice appear in
#  supporting documentation.
#
# x3270, c3270, s3270 and tcl3270 are distributed in the hope that they will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the file LICENSE
# for more details.

# Generate a .lsm file.

if [ $# -ne 1 ]
then	echo >&2 "usage: $0 <modname>"
	exit 1
fi
if [ ! -f $1.tgz ]
then	echo >&2 "$1.tgz not found"
	exit 1
fi
if [ ! -f $1.lsm.tmpl ]
then	echo >&2 "$1.lsm.tmpl not found"
	exit 1
fi

# Set up the temp file
tf=/tmp/tgz$$

# Set up the variables
source version.txt
VERSION=$version
EDATE=$(date "+%Y-%m-%d")
SIZE=$(ls -l $1.tgz | awk '{x=$5; print int((x+500)/1000);}')

sed <$1.lsm.tmpl \
	-e "s/\$VERSION/$VERSION/g" \
	-e "s/\$EDATE/$EDATE/g" \
	-e "s/\$SIZE/$SIZE/g" >$tf

if [ -r $1 ] && diff $1.lsm $tf >/dev/null
then	:
else	[ -r $1.lsm -a ! -w $1.lsm ] && co -l $1.lsm
	cp $tf $1.lsm
fi
rm -f $tf
