#! /bin/sh

# Copyright (c) 1995-2009, Paul Mattes.
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Paul Mattes nor his contributors may be used
#       to endorse or promote products derived from this software without
#       specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY PAUL MATTES "AS IS" AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
# NO EVENT SHALL PAUL MATTES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Run x3270 from the current directory

# Bomb on any error
set -e
d=`pwd`

# Say what you're doing
set -x

# Set up the fonts
mkfontdir .
xset +fp $d/
xset fp rehash

# Set up the dynamic library path
if [ -d /usr/openwin/lib ]
then  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/openwin/lib
fi
if [ -d /usr/ucblib ]
then  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/ucblib
fi
export LD_LIBRARY_PATH

# Set up the PATH to include pr3287.
PATH=$PATH:$d/pr3287
export PATH

# Set up ICU_DATA, for DBCS translations.
ICU_DATA=.:$ICU_DATA
export ICU_DATA

# Run x3270, pointing it to the current directory for its configuration files
set +e
./x3270 -xrm "x3270.confDir: $d" "$@"

# Clean up
xset -fp $d/
xset fp rehash
