ALL = c3270-dir pr3287-dir s3270-dir tcl3270-dir wc3270-dir Webpage-dir \
	wpr3287-dir ws3270-dir x3270-dir

all: $(ALL)

.fake: $(ALL)

c3270-dir:
	cd c3270 && mk

pr3287-dir:
	cd pr3287 && mk

s3270-dir:
	cd s3270 && mk

tcl3270-dir:
	cd tcl3270 && mk

wc3270-dir:
	cd wc3270 && mk

Webpage-dir:
	cd Webpage && mk

wpr3287-dir:
	cd wpr3287 && mk

ws3270-dir:
	cd ws3270 && mk

x3270-dir:
	cd x3270 && mk
