'\" t
.TH x3270 1 "02 July 2024"
.SH "NAME"
x3270 \-
\s-1IBM\s+1 host access tool
.SH "SYNOPSIS"
\fBx3270\fP
[\fIoptions\fP]
[\fIhost\fP]
.br
\fBx3270\fP [\fIoptions\fP] \fIsession-file\fP.x3270
.SH "DESCRIPTION"
\fBx3270\fP opens a telnet connection to an \s-1IBM\s+1
host in an X window.
It implements RFCs 2355 (TN3270E), 1576 (TN3270) and 1646 (LU name selection),
and supports IND$FILE file transfer.
The window created by \fBx3270\fP
can use its own font for displaying characters, so it is a fairly accurate
representation of an \s-1IBM\s+1 3278 or 3279.
It is similar to \fItn3270\fP(1) except that it is X11-based, not curses-based.
.SH "WIKI"
Primary documentation for x3270 is on the \fBx3270 Wiki\fP, https://x3270.miraheze.org/wiki/Main_Page.
.SH "VERSION"
x3270 4.4pre1
