all:
	cd 3270 && $(MAKE) $@
	cd 3270stubs && $(MAKE) $@
	cd w3270 && $(MAKE) $@
	cd w3270stubs && $(MAKE) $@

clean:
	cd 3270 && $(MAKE) $@
	cd 3270stubs && $(MAKE) $@
	cd w3270 && $(MAKE) $@
	cd w3270stubs && $(MAKE) $@

depend:
	cd 3270 && $(MAKE) $@
	cd 3270stubs && $(MAKE) $@
	cd w3270 && $(MAKE) $@
	cd w3270stubs && $(MAKE) $@
