#!/usr/local/bin/bash
# Copyright (c) 2000-2009, Paul Mattes.
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Paul Mattes nor his contributors may be used
#       to endorse or promote products derived from this software without
#       specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY PAUL MATTES "AS IS" AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
# NO EVENT SHALL PAUL MATTES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Generate a .man or -man.html file.

if [ $# -ne 1 ]
then	echo >&2 "usage: $0 <filename>"
	exit 1
fi
if [ ! -f $1.tmpl ]
then	echo >&2 "$1.tmpl not found"
	exit 1
fi

# Set up the temp file
tf=/tmp/tgz$$

# Set up the variables
source version.txt
VERSION=$version
DATE=$(date "+%d %B %Y" | sed 's/^0//')

sed <$1.tmpl \
	-e "s/\$VERSION/$VERSION/g" \
	-e "s/\$DATE/$DATE/g" >$tf

if [ -r $1 ] && diff $1 $tf >/dev/null
then	:
else	[ -r $1 -a ! -w $1 ] && co -l $1
	cp $tf $1
fi
rm -f $tf
