#!/bin/sh
# generate an html man page from m4 source
. ./version.txt
date=`date "+%d %B %Y"`
product=$1
# platform
case $product in
    x3270|x3270|s3270|tcl3270|pr3287)
	platform=unix
	c3270=c3270
	s3270=s3270
	pr3287=pr3287
	x3270=x3270
	;;
    wc3270|ws3270|wpr3287)
	platform=windows
	c3270=wc3270
	s3270=ws3270
	pr3287=wpr3287
	x3270=wc3270
	;;
*)
    echo >&2 "Unknown product: $1"
    exit 1
esac
# mode
case $product in
    c3270|wc3270)
	mode=console
	;;
    s3270|ws3270)
	mode=script
	;;
    *)
	mode=$product
	;;
esac
# interactive
case $product in
    x3270|c3270|wc3270)
	interactive=yes
	;;
    *)
	interactive=no
	;;
esac

/usr/bin/m4 -DXX_PRODUCT=$product -DXX_PAGENAME=$2 \
    -DXX_PLATFORM=$platform -DXX_MODE=$mode -DXX_INTERACTIVE=$interactive \
    -DXX_C3270=$c3270 -DXX_S3270=$s3270 -DXX_PR3287=$pr3287 -DXX_X3270=$x3270 \
    -DXX_DATE="$date" -DXX_VERSION_NUMBER=$version html.m4 $3
